# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm run build
  displayName: 'npm run build'

- script: npm run deploy -- --user=\"ProcessEngineCI <hello@process-engine.io>\" --repo=https://${GH_TOKEN}@github.com/process-engine/process-engine.github.io.git
  displayName: 'npm run deploy'
  env:
    GH_TOKEN: $(GH_TOKEN)
