name: Repository Dispatch
on:
  push:
    branches:
      - "*"
      - "*/*"
  repository_dispatch:
    types: [release_was_published]
jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: echo ${{ github.event.client_payload.sha }}