name: Deploy on Studio Release

on:
  push:
    branches:
      - develop
  repository_dispatch:
    types: [release_was_published]

jobs:
  deploy_website:
    name: "Deploy ProcessEngine.io"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Dependencies
        run: npm ci

      - name: Build Sources
        run: npm run build

      - name: Deploy
        run: npm run deploy -- --user="ProcessEngineCI <hello@process-engine.io>" --repo=https://${GH_TOKEN}@github.com/process-engine/process-engine.github.io.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
